import OpenAI from 'openai';
export const openai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
export const model=process.env.OPENAI_MODEL||'gpt-4o-mini';
const questionSchema={type:'object',additionalProperties:false,properties:{title:{type:'string'},difficulty:{type:'string',enum:['beginner','intermediate','advanced','very-advanced']},topic:{type:'string'},context:{type:'string'},task:{type:'string'},required_output:{type:'string'},reference_sql:{type:'string'},tags:{type:'array',items:{type:'string'}}},required:['title','difficulty','topic','context','task','required_output','reference_sql','tags']};
const batchSchema={type:'object',additionalProperties:false,properties:{questions:{type:'array',items:questionSchema}},required:['questions']};
const imageSchema={type:'object',additionalProperties:false,properties:{sql:{type:'string'},sampleDataSql:{type:'string'},sampleDataSource:{type:'string',enum:['generated','none']},databaseName:{type:'string'},tables:{type:'array',items:{type:'object',additionalProperties:false,properties:{name:{type:'string'},columns:{type:'array',items:{type:'string'}}},required:['name','columns']}},warnings:{type:'array',items:{type:'string'}}},required:['sql','sampleDataSql','sampleDataSource','databaseName','tables','warnings']};
export async function generateQuestions(schemaText:string,count:number,difficulty:string,topic:string){if(!openai)throw new Error('OPENAI_API_KEY is not configured');const prompt=`Generate rigorous SQL interview practice questions from the EXACT PostgreSQL schema below. Never invent a table/column. Each reference_sql must be a single SELECT/WITH query executable against this schema. Avoid duplicate intent. Difficulty=${difficulty}; topic=${topic}; count=${count}. Questions should be distinct in reasoning, not just different wording. Return only structured data.\nSCHEMA:\n${schemaText}`;const r=await openai.responses.create({model,input:prompt,text:{format:{type:'json_schema',name:'sql_question_batch',strict:true,schema:batchSchema}}});return JSON.parse(r.output_text) as {questions:any[]}}
export async function extractSchemaFromImage(dataUrl:string){if(!openai)throw new Error('OPENAI_API_KEY is not configured');const prompt='Inspect this schema screenshot and create a reviewable PostgreSQL practice database plan. In sql, return only CREATE TABLE statements for tables and columns that are visible; preserve visible types, primary keys, foreign keys, nullability, and relationships. Do not invent schema objects. Write primary keys as table-level PRIMARY KEY constraints. Write every foreign key as a separate table-level constraint after all column definitions, for example CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id). Never put FOREIGN KEY after a column type. Create referenced parent tables before child tables. In sampleDataSql, generate exactly 8 realistic, varied synthetic practice rows for each table using only the declared columns. Do not generate more than 10 rows for any table, and never copy sample row values from the screenshot. Satisfy types, unique keys, and foreign-key references. Mark sampleDataSource as generated when tables are identified, or none only if no table is identifiable. Never put INSERT statements in sql. State in warnings that sample rows are synthetic AI-generated data. Return empty sql and sampleDataSql only when no table can be identified.';const r=await openai.responses.create({model,input:[{role:'user',content:[{type:'input_text',text:prompt},{type:'input_image',image_url:dataUrl,detail:'auto'}]}],text:{format:{type:'json_schema',name:'schema_import_plan',strict:true,schema:imageSchema}}});return JSON.parse(r.output_text) as {sql:string;sampleDataSql:string;sampleDataSource:'generated'|'none';databaseName:string;tables:{name:string;columns:string[]}[];warnings:string[]}}
export async function tutor(action:string,question:string,schema:string,sql:string,error?:string){if(!openai)throw new Error('OPENAI_API_KEY is not configured');const prompt=`You are an expert SQL tutor. Action=${action}. Use only the supplied schema. Prefer progressive hints. Do not invent schema. Do not reveal the final query unless explicitly requested. QUESTION:${question}\nSCHEMA:${schema}\nUSER SQL:${sql}\nERROR:${error||'none'}`;const r=await openai.responses.create({model,input:prompt});return r.output_text}
const sampleDataPatchSchema={type:'object',additionalProperties:false,properties:{sql:{type:'string'}},required:['sql']};
export async function generateAdditionalSampleRows(schemaSql:string,currentDataSql:string,missing:{table:string;missingRows:number}[]){if(!openai)throw new Error('OPENAI_API_KEY is not configured');const prompt=`Generate only PostgreSQL INSERT statements that add the requested missing sample rows. Use exactly the listed existing table names and columns from this schema. Do not recreate tables, delete/update existing rows, or use conflict-ignore. Generate unique primary keys and values that respect foreign keys. Current data is already inserted; avoid duplicating its primary keys. The target is a minimum of 20 rows per table. Missing row counts: ${JSON.stringify(missing)}\nSCHEMA DDL:\n${schemaSql}\nEXISTING SAMPLE INSERTS (avoid these primary-key values):\n${currentDataSql}`;const r=await openai.responses.create({model,input:prompt,text:{format:{type:'json_schema',name:'additional_sample_rows',strict:true,schema:sampleDataPatchSchema}}});return JSON.parse(r.output_text) as {sql:string}}
