import crypto from 'node:crypto';
import { pool, executeReadOnly } from './db.js';
export async function seedAdmin(){const email=(process.env.ADMIN_EMAIL||'admin@sqlpractice.local').toLowerCase();const r=await pool.query('SELECT id FROM users WHERE email=$1',[email]);if(r.rowCount)return;const {hashPassword}=await import('./auth.js');await pool.query('INSERT INTO users(id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5)',[crypto.randomUUID(),process.env.ADMIN_NAME||'Platform Admin',email,hashPassword(process.env.ADMIN_PASSWORD||'ChangeMe!123'),'admin'])}
export async function seedStarterQuestions(){const database=(await pool.query("SELECT * FROM app_databases WHERE slug='demo-ecommerce'")).rows[0];if(!database)return;const existing=await pool.query('SELECT 1 FROM challenges WHERE database_id=$1 LIMIT 1',[database.id]);if(existing.rowCount){await pool.query("UPDATE challenges SET difficulty='very-advanced' WHERE database_id=$1 AND source='starter' AND title='Find the highest-paid employee in each department' AND difficulty='advanced'",[database.id]);return}const items=[
 {title:'Find an employee by first name',difficulty:'beginner',topic:'WHERE',context:'An HR analyst needs to locate a specific employee record.',task:'Find the employee whose first name is Amit.',required:'Return first_name, last_name, salary, and department_id.',sql:"SELECT first_name,last_name,salary,department_id FROM employees WHERE first_name='Amit' ORDER BY employee_id",tags:['filtering','where']},
 {title:'Filter employees above a salary threshold',difficulty:'beginner',topic:'Filtering',context:'The compensation team is reviewing employees earning at least 70000.',task:'List employees whose salary is at least 70000.',required:'Return employee_id, first_name, and salary ordered by salary descending.',sql:'SELECT employee_id,first_name,salary FROM employees WHERE salary>=70000 ORDER BY salary DESC,employee_id',tags:['filtering','comparison']},
 {title:'Join employees to department names',difficulty:'beginner',topic:'JOINs',context:'A report needs readable department names instead of department IDs.',task:'Show each employee and their department.',required:'Return first_name, last_name, department_name in that order.',sql:'SELECT e.first_name,e.last_name,d.department_name FROM employees e JOIN departments d ON d.department_id=e.department_id ORDER BY e.employee_id',tags:['join','foreign keys']},
 {title:'Average salary by department',difficulty:'intermediate',topic:'GROUP BY',context:'Leadership is comparing average salaries across departments.',task:'Calculate the average salary for every department.',required:'Return department_name and average_salary ordered by department_id.',sql:'SELECT d.department_name,AVG(e.salary) AS average_salary FROM departments d JOIN employees e ON e.department_id=d.department_id GROUP BY d.department_id,d.department_name ORDER BY d.department_id',tags:['aggregation','group by']},
 {title:'Count employees in each department',difficulty:'intermediate',topic:'LEFT JOIN',context:'A staffing report must retain departments even if they have no employees.',task:'Count employees per department.',required:'Return department_name and employee_count, including zero-count departments.',sql:'SELECT d.department_name,COUNT(e.employee_id)::int AS employee_count FROM departments d LEFT JOIN employees e ON e.department_id=d.department_id GROUP BY d.department_id,d.department_name ORDER BY d.department_id',tags:['left join','count']},
 {title:'Find employees above the company average',difficulty:'intermediate',topic:'CTEs',context:'An analyst is identifying employees earning above the overall average.',task:'Return employees whose salary is greater than the company-wide average.',required:'Return employee_id, first_name, salary ordered by salary descending.',sql:'WITH company_average AS (SELECT AVG(salary) AS avg_salary FROM employees) SELECT e.employee_id,e.first_name,e.salary FROM employees e CROSS JOIN company_average a WHERE e.salary>a.avg_salary ORDER BY e.salary DESC,e.employee_id',tags:['cte','subquery','aggregation']},
 {title:'Rank salaries within each department',difficulty:'advanced',topic:'Window Functions',context:'HR wants to compare salary rank without collapsing employee rows.',task:'Rank employees by salary within their department.',required:'Return department_id, first_name, salary, salary_rank ordered by department_id and rank.',sql:'SELECT department_id,first_name,salary,DENSE_RANK() OVER(PARTITION BY department_id ORDER BY salary DESC) AS salary_rank FROM employees ORDER BY department_id,salary_rank,employee_id',tags:['window function','dense rank']},
 {title:'Check for missing employee last names',difficulty:'beginner',topic:'NULL Handling',context:'A data-quality check looks for employee records without a last name.',task:'Find employees whose last_name is NULL.',required:'Return employee_id, first_name, and last_name.',sql:'SELECT employee_id,first_name,last_name FROM employees WHERE last_name IS NULL ORDER BY employee_id',tags:['null','data quality']},
 {title:'List distinct job titles',difficulty:'beginner',topic:'DISTINCT',context:'A workforce dashboard needs a unique list of available job titles.',task:'Return each job title once.',required:'Return one column named job_title in alphabetical order.',sql:'SELECT DISTINCT job_title FROM jobs ORDER BY job_title',tags:['distinct','sorting']},
 {title:'Find exclusion rules with no blocked job',difficulty:'beginner',topic:'Data Quality',context:'The rules pipeline needs to review exclusions that are not linked to a job.',task:'Find rules where blocked_job_id is missing.',required:'Return rule_id, blocked_job_id, and reason.',sql:'SELECT rule_id,blocked_job_id,reason FROM exclusion_rules WHERE blocked_job_id IS NULL ORDER BY rule_id',tags:['null','data quality']},
 {title:'Compare employee salaries with job bands',difficulty:'advanced',topic:'Data Quality',context:'Compensation data must stay within the configured minimum and maximum for each job.',task:'Find employees whose salary falls outside their job band.',required:'Return employee_id, first_name, salary, min_salary, max_salary ordered by employee_id.',sql:'SELECT e.employee_id,e.first_name,e.salary,j.min_salary,j.max_salary FROM employees e JOIN jobs j ON j.job_id=e.job_id WHERE e.salary<j.min_salary OR e.salary>j.max_salary ORDER BY e.employee_id',tags:['join','validation']},
 {title:'Find the highest-paid employee in each department',difficulty:'very-advanced',topic:'Window Functions',context:'Department leaders need one top-paid employee per department.',task:'Return the highest-paid employee from each department.',required:'Return department_name, first_name, salary with one row per department.',sql:'WITH ranked AS (SELECT d.department_name,e.first_name,e.salary,ROW_NUMBER() OVER(PARTITION BY d.department_id ORDER BY e.salary DESC,e.employee_id) AS row_num FROM departments d JOIN employees e ON e.department_id=d.department_id) SELECT department_name,first_name,salary FROM ranked WHERE row_num=1 ORDER BY department_name',tags:['window function','row number']}
];const client=await pool.connect();try{await client.query('BEGIN');const setId=crypto.randomUUID();await client.query('INSERT INTO question_sets(id,database_id,name,count_requested,accepted_count,status,settings) VALUES($1,$2,$3,$4,$5,$6,$7)',[setId,database.id,'SQL Foundations · Data Engineering',items.length,0,'running',JSON.stringify({source:'starter',topics:[...new Set(items.map(item=>item.topic))]})]);const ids=[];for(const item of items){const expected=await executeReadOnly(database.schema_name,item.sql),id=crypto.randomUUID();await client.query('INSERT INTO challenges(id,database_id,question_set_id,title,difficulty,topic,context,task,required_output,reference_sql,expected_json,tags,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[id,database.id,setId,item.title,item.difficulty,item.topic,item.context,item.task,item.required, item.sql,JSON.stringify(expected),JSON.stringify(item.tags),'starter']);ids.push(id)}await client.query('UPDATE question_sets SET accepted_count=$1,status=$2 WHERE id=$3',[ids.length,'completed',setId]);const collectionId=crypto.randomUUID();await client.query('INSERT INTO question_collections(id,database_id,name,description,is_published) VALUES($1,$2,$3,$4,$5)',[collectionId,database.id,'Company Challenge · Workforce Data Quality','Original workforce SQL challenges for data-engineering practice.',true]);for(let i=0;i<ids.length;i++)await client.query('INSERT INTO collection_questions(collection_id,challenge_id,position) VALUES($1,$2,$3)',[collectionId,ids[i],i]);await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
export async function metrics(){const [u,q,a,s]=await Promise.all([pool.query("SELECT count(*)::int total, count(*) FILTER(WHERE status='active')::int active FROM users"),pool.query('SELECT count(*)::int total,count(*) FILTER(WHERE source=\'ai\')::int ai FROM challenges'),pool.query('SELECT count(*)::int attempts,count(*) FILTER(WHERE correct)::int correct,coalesce(round(avg(execution_ms)),0)::int avg_ms FROM attempts'),pool.query("SELECT count(*)::int total FROM app_databases")]);return {users:u.rows[0],questions:q.rows[0],attempts:a.rows[0],databases:s.rows[0]}}
